# Process simulation campaign with blueetl

In [1]:
from blueetl.analysis import run_from_file
analysis_config_file = "analysis_config_01_relative_with_soma.yaml"
loglevel = "INFO"
ma = run_from_file(analysis_config_file, loglevel=loglevel)
# ma = ma.apply_filter()

2025-05-06 11:04:04,664 INFO blueetl.analysis: MultiAnalyzer configuration: analysis_config_01_relative_with_soma.yaml
2025-05-06 11:04:04,695 INFO blueetl.cache: Loading cached checksums from analysis_output/spikes/config/checksums.cached.yaml
2025-05-06 11:04:04,696 INFO blueetl.cache: Initialize cache
2025-05-06 11:04:04,702 INFO blueetl.cache: Loading cached checksums from analysis_output/soma/config/checksums.cached.yaml
2025-05-06 11:04:04,703 INFO blueetl.cache: Initialize cache
2025-05-06 11:04:04,744 INFO blueetl.extract.simulations: Simulations extracted: 1/1, ids: [0]
2025-05-06 11:04:04,752 INFO blueetl.extract.simulations: Simulations extracted: 1/1, ids: [0]
2025-05-06 11:04:04,758 INFO blueetl.features: Step 1: grouping features by attributes...
2025-05-06 11:04:04,758 INFO blueetl.features: Preprocessing features 1/1 [id=0]
2025-05-06 11:04:04,758 INFO blueetl.features: Step 1: grouping features by attributes [DONE in 0.00 seconds]
2025-05-06 11:04:04,758 INFO blueetl.features: Step 2: processing cached features...
2025-05-06 11:04:04,765 INFO blueetl.features: Calculated features 1/1 [id=0]
- by_gid: cached=True, filtered=False
- by_gid_and_trial: cached=True, filtered=False
- by_neuron_class: cached=True, filtered=False
- by_neuron_class_and_trial: cached=True, filtered=False
- histograms: cached=True, filtered=False
2025-05-06 11:04:04,765 INFO blueetl.features: Step 2: processing cached features [DONE in 0.01 seconds]
2025-05-06 11:04:04,765 INFO blueetl.features: Step 3: processing new features...
2025-05-06 11:04:04,765 INFO blueetl.features: Step 3: processing new features [DONE in 0.00 seconds]
2025-05-06 11:04:04,766 INFO blueetl.features: Features calculation completed
2025-05-06 11:04:04,782 INFO blueetl.features: Step 1: grouping features by attributes...
2025-05-06 11:04:04,782 INFO blueetl.features: Preprocessing features 1/1 [id=0]
2025-05-06 11:04:04,783 INFO blueetl.features: Step 1: grouping features by attributes [DONE in 0.00 seconds]
2025-05-06 11:04:04,783 INFO blueetl.features: Step 2: processing cached features...
2025-05-06 11:04:04,785 INFO blueetl.features: Calculated features 1/1 [id=0]
- by_neuron_class: cached=True, filtered=False
2025-05-06 11:04:04,785 INFO blueetl.features: Step 2: processing cached features [DONE in 0.00 seconds]
2025-05-06 11:04:04,785 INFO blueetl.features: Step 3: processing new features...
2025-05-06 11:04:04,785 INFO blueetl.features: Step 3: processing new features [DONE in 0.00 seconds]
2025-05-06 11:04:04,785 INFO blueetl.features: Features calculation completed

# Blueetl has created two analyzer objects for the spikes and soma blocks in the configuration file

In [2]:
# print(ma.analyzers)

# View the dataframes created for the spikes analyzer
- These are divided into "repo" and "features" dataframes.

- Repo dataframes are standard dataframes which organize the basic simualtion information and data.

- Features dataframes are calculated from the initial repo dataframes by code provided by the user, and typically store calcualted metrics or vectors such as PSTHs

In [3]:
spikes_analyzer = ma.analyzers["spikes"]

print(spikes_analyzer.repo.report.df)
print(spikes_analyzer.repo.neuron_classes.df)
print(spikes_analyzer.repo.simulations.df)
print(spikes_analyzer.repo.neurons.df)
print(spikes_analyzer.repo.windows.df)

print(spikes_analyzer.features.names)
print(spikes_analyzer.features.by_gid.df)
print(spikes_analyzer.features.by_gid_and_trial.df)
print(spikes_analyzer.features.by_neuron_class.df)
print(spikes_analyzer.features.by_neuron_class_and_trial.df)
print(spikes_analyzer.features.histograms.df)

   time  gid window  trial  simulation_id  circuit_id neuron_class
0   0.1    2     w1      0              0           0          All
1   0.2    0     w1      0              0           0          All
2   0.3    1     w1      0              0           0          All
3   0.7    2     w1      0              0           0          All
4   0.2    0     w1      0              0           0         L2_X
5   0.1    2     w1      0              0           0         L6_Y
6   0.3    1     w1      0              0           0         L6_Y
7   0.7    2     w1      0              0           0         L6_Y
   circuit_id neuron_class  count  limit population node_set  gids  \
0           0          All      3   1000    default     None  None
1           0         L2_X      1   1000    default     None  None
2           0         L6_Y      2   1000    default     None  None

                 query
0                   {}
1  {"mtype": ["L2_X"]}
2  {"mtype": ["L6_Y"]}
     seed                                    simulation_path  simulation_id  \
0  334630  /Users/mandge/Desktop/obi/repos/obi-one/exampl...              0

   circuit_id                                         simulation  \
0           0  <blueetl.adapters.simulation.SimulationAdapter...

                                             circuit
0  <blueetl.adapters.circuit.CircuitAdapter objec...
   circuit_id neuron_class  gid  neuron_class_index
0           0          All    0                   0
1           0          All    1                   1
2           0          All    2                   2
3           0         L2_X    0                   0
4           0         L6_Y    1                   0
5           0         L6_Y    2                   1
   simulation_id  circuit_id window  trial  offset  t_start  t_stop  t_step  \
0              0           0     w1      0     0.0      0.0     1.0     0.0

   duration  window_type
0       1.0  spontaneous
['by_gid', 'by_gid_and_trial', 'by_neuron_class', 'by_neuron_class_and_trial', 'histograms']
                                                                     first_spike_time_means_cort_zeroed  \
simulation_id circuit_id neuron_class window gid neuron_class_index
0             0          All          w1     0   0                                                  0.2
                                             1   1                                                  0.3
                                             2   2                                                  0.1
                         L2_X         w1     0   0                                                  0.2
                         L6_Y         w1     1   0                                                  0.3
                                             2   1                                                  0.1

                                                                     mean_spike_counts  \
simulation_id circuit_id neuron_class window gid neuron_class_index
0             0          All          w1     0   0                                 1.0
                                             1   1                                 1.0
                                             2   2                                 2.0
                         L2_X         w1     0   0                                 1.0
                         L6_Y         w1     1   0                                 1.0
                                             2   1                                 2.0

                                                                     mean_firing_rates_per_second
simulation_id circuit_id neuron_class window gid neuron_class_index
0             0          All          w1     0   0                                         1000.0
                                             1   1                                         1000.0
                                             2   2                                         2000.0
                         L2_X         w1     0   0                                         1000.0
                         L6_Y         w1     1   0                                         1000.0
                                             2   1                                         2000.0
                                                                           count  \
simulation_id circuit_id neuron_class window trial gid neuron_class_index
0             0          All          w1     0     0   0                       1
                                                   1   1                       1
                                                   2   2                       2
                         L2_X         w1     0     0   0                       1
                         L6_Y         w1     0     1   0                       1
                                                   2   1                       2

                                                                           first  \
simulation_id circuit_id neuron_class window trial gid neuron_class_index
0             0          All          w1     0     0   0                     0.2
                                                   1   1                     0.3
                                                   2   2                     0.1
                         L2_X         w1     0     0   0                     0.2
                         L6_Y         w1     0     1   0                     0.3
                                                   2   1                     0.1

                                                                                times
simulation_id circuit_id neuron_class window trial gid neuron_class_index
0             0          All          w1     0     0   0                        [0.2]
                                                   1   1                        [0.3]
                                                   2   2                   [0.1, 0.7]
                         L2_X         w1     0     0   0                        [0.2]
                         L6_Y         w1     0     1   0                        [0.3]
                                                   2   1                   [0.1, 0.7]
                                              mean_of_mean_spike_counts  \
simulation_id circuit_id neuron_class window
0             0          All          w1                       1.333333
                         L2_X         w1                       1.000000
                         L6_Y         w1                       1.500000

                                              mean_of_mean_firing_rates_per_second  \
simulation_id circuit_id neuron_class window
0             0          All          w1                               1333.333333
                         L2_X         w1                               1000.000000
                         L6_Y         w1                               1500.000000

                                              std_of_mean_firing_rates_per_second  \
simulation_id circuit_id neuron_class window
0             0          All          w1                               471.404521
                         L2_X         w1                                 0.000000
                         L6_Y         w1                               500.000000

                                              mean_of_spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window
0             0          All          w1                                         1.333333
                         L2_X         w1                                         1.000000
                         L6_Y         w1                                         1.500000

                                              min_of_spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window
0             0          All          w1                                        1.333333
                         L2_X         w1                                        1.000000
                         L6_Y         w1                                        1.500000

                                              max_of_spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window
0             0          All          w1                                        1.333333
                         L2_X         w1                                        1.000000
                         L6_Y         w1                                        1.500000

                                              argmax_spike_times_hist_1ms_bin
simulation_id circuit_id neuron_class window
0             0          All          w1                                    0
                         L2_X         w1                                    0
                         L6_Y         w1                                    0
                                                    mean_of_spike_counts_for_each_trial
simulation_id circuit_id neuron_class window trial
0             0          All          w1     0                                 1.333333
                         L2_X         w1     0                                 1.000000
                         L6_Y         w1     0                                 1.500000
                                                  spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window bin
0             0          All          w1     0                               1.333333
                         L2_X         w1     0                               1.000000
                         L6_Y         w1     0                               1.500000

                                                  spike_times_max_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window bin
0             0          All          w1     0                                        1.0
                         L2_X         w1     0                                        1.0
                         L6_Y         w1     0                                        1.0

                                                  smoothed_3ms_spike_times_max_normalised_hist_1ms_bin
simulation_id circuit_id neuron_class window bin
0             0          All          w1     0                                                  1.0
                         L2_X         w1     0                                                  1.0
                         L6_Y         w1     0                                                  1.0

# Example blueetl filtering of dataframes

In [4]:
spikes_analyzer.repo.report.df.etl.q(neuron_class='L2_X', window='w2')

Empty DataFrame
Columns: [time, gid, window, trial, simulation_id, circuit_id, neuron_class]
Index: []

# View the dataframes created for the soma analyzer

In [5]:
soma_report_analyzer = ma.analyzers["soma"]

print(soma_report_analyzer.repo.report.df)
print(soma_report_analyzer.repo.neuron_classes.df)
print(soma_report_analyzer.repo.simulations.df)
print(soma_report_analyzer.repo.neurons.df)
print(soma_report_analyzer.repo.windows.df)

print(soma_report_analyzer.features.names)
print(soma_report_analyzer.features.by_neuron_class.df)

   gid  time  value window  trial  simulation_id  circuit_id neuron_class
0    0   0.0    0.0     w1      0              0           0         L2_X
1    0   0.1    0.1     w1      0              0           0         L2_X
2    0   0.2    0.2     w1      0              0           0         L2_X
3    0   0.3    0.3     w1      0              0           0         L2_X
4    0   0.4    0.4     w1      0              0           0         L2_X
5    0   0.5    0.5     w1      0              0           0         L2_X
6    0   0.6    0.6     w1      0              0           0         L2_X
7    0   0.7    0.7     w1      0              0           0         L2_X
8    0   0.8    0.8     w1      0              0           0         L2_X
9    0   0.9    0.9     w1      0              0           0         L2_X
   circuit_id neuron_class  count  limit population node_set  gids  \
0           0         L2_X      1   1000    default     None  None

                 query
0  {"mtype": ["L2_X"]}
     seed                                    simulation_path  simulation_id  \
0  334630  /Users/mandge/Desktop/obi/repos/obi-one/exampl...              0

   circuit_id                                         simulation  \
0           0  <blueetl.adapters.simulation.SimulationAdapter...

                                             circuit
0  <blueetl.adapters.circuit.CircuitAdapter objec...
   circuit_id neuron_class  gid  neuron_class_index
0           0         L2_X    0                   0
   simulation_id  circuit_id window  trial  offset  t_start  t_stop  t_step  \
0              0           0     w1      0     0.0      0.0     1.0     0.0

   duration  window_type
0       1.0  spontaneous
['by_neuron_class']
                         neuron_class window  mean       std
simulation_id circuit_id
0             0                  L2_X     w1  0.45  0.302765

In [6]:
for feature_name in soma_report_analyzer.features.names:
    print(feature_name)
    print(soma_report_analyzer.features._data[feature_name].df)

by_neuron_class
                         neuron_class window  mean       std
simulation_id circuit_id
0             0                  L2_X     w1  0.45  0.302765

Let's get the soma report dataframe to see the time and voltage (value) arrays. We will them to generate a timeseries trace array to extract eFEL features. Here, we create a dataframe `soma_df`to easily access the entries.

In [7]:
soma_report_analyzer.repo.report.df
soma_df = soma_report_analyzer.repo.report.df
soma_df

   gid  time  value window  trial  simulation_id  circuit_id neuron_class
0    0   0.0    0.0     w1      0              0           0         L2_X
1    0   0.1    0.1     w1      0              0           0         L2_X
2    0   0.2    0.2     w1      0              0           0         L2_X
3    0   0.3    0.3     w1      0              0           0         L2_X
4    0   0.4    0.4     w1      0              0           0         L2_X
5    0   0.5    0.5     w1      0              0           0         L2_X
6    0   0.6    0.6     w1      0              0           0         L2_X
7    0   0.7    0.7     w1      0              0           0         L2_X
8    0   0.8    0.8     w1      0              0           0         L2_X
9    0   0.9    0.9     w1      0              0           0         L2_X

Let's create a dictionary with the time and voltage arrays, start and end times.

In [8]:
import efel

# Extract time and voltage arrays
time = soma_df['time'].to_numpy()
voltage = soma_df['value'].to_numpy()

# Convert time to seconds
time = time * 1000  # Assuming time is in ms
# convert the voltage to mV
voltage = voltage * 1000

# Create trace dictionary for eFEL
trace = {
    'T': time,
    'V': voltage,
    'stim_start': [700],  # Adjust these values based on your simulation
    'stim_end': [2700]    # Adjust these values based on your simulation
}

# Create traces list and set eFEL settings
traces = [trace]
efel.set_setting('Threshold', -20)

# Extract features
feature_names = ['voltage_base']  # Add more features as needed
traces_results = efel.get_feature_values(traces, feature_names)

# Print results
for trace_results in traces_results:
    for feature_name, feature_values in trace_results.items():
        print(f"Feature {feature_name} has values: {feature_values}")

Feature voltage_base has values: [665.]

Similarly you can use other efel featuers on soma reports

In [9]:
efel.get_feature_names()

['ADP_peak_amplitude',
 'ADP_peak_indices',
 'ADP_peak_values',
 'AHP1_depth_from_peak',
 'AHP2_depth_from_peak',
 'AHP_depth',
 'AHP_depth_abs',
 'AHP_depth_abs_slow',
 'AHP_depth_diff',
 'AHP_depth_from_peak',
 'AHP_depth_slow',
 'AHP_slow_time',
 'AHP_time_from_peak',
 'AP1_amp',
 'AP1_begin_voltage',
 'AP1_begin_width',
 'AP1_peak',
 'AP1_width',
 'AP2_AP1_begin_width_diff',
 'AP2_AP1_diff',
 'AP2_AP1_peak_diff',
 'AP2_amp',
 'AP2_begin_voltage',
 'AP2_begin_width',
 'AP2_peak',
 'AP2_width',
 'AP_amplitude',
 'AP_amplitude_change',
 'AP_amplitude_diff',
 'AP_amplitude_from_voltagebase',
 'AP_begin_indices',
 'AP_begin_time',
 'AP_begin_voltage',
 'AP_begin_width',
 'AP_duration',
 'AP_duration_change',
 'AP_duration_half_width',
 'AP_duration_half_width_change',
 'AP_end_indices',
 'AP_fall_indices',
 'AP_fall_rate',
 'AP_fall_rate_change',
 'AP_fall_time',
 'AP_height',
 'AP_peak_downstroke',
 'AP_peak_upstroke',
 'AP_phaseslope',
 'AP_rise_indices',
 'AP_rise_rate',
 'AP_rise_rate_change',
 'AP_rise_time',
 'AP_width',
 'AP_width_between_threshold',
 'APlast_amp',
 'APlast_width',
 'adaptation_index',
 'adaptation_index2',
 'all_ISI_values',
 'amp_drop_first_last',
 'amp_drop_first_second',
 'amp_drop_second_last',
 'burst_begin_indices',
 'burst_end_indices',
 'current',
 'current_base',
 'decay_time_constant_after_stim',
 'depolarized_base',
 'doublet_ISI',
 'fast_AHP',
 'fast_AHP_change',
 'interburst_15percent_indices',
 'interburst_15percent_values',
 'interburst_20percent_indices',
 'interburst_20percent_values',
 'interburst_25percent_indices',
 'interburst_25percent_values',
 'interburst_30percent_indices',
 'interburst_30percent_values',
 'interburst_40percent_indices',
 'interburst_40percent_values',
 'interburst_60percent_indices',
 'interburst_60percent_values',
 'interburst_duration',
 'interburst_min_indices',
 'interburst_min_values',
 'inv_time_to_first_spike',
 'is_not_stuck',
 'max_amp_difference',
 'maximum_voltage',
 'maximum_voltage_from_voltagebase',
 'mean_AP_amplitude',
 'mean_frequency',
 'min_AHP_indices',
 'min_AHP_values',
 'min_between_peaks_indices',
 'min_between_peaks_values',
 'min_voltage_between_spikes',
 'minimum_voltage',
 'multiple_decay_time_constant_after_stim',
 'number_initial_spikes',
 'ohmic_input_resistance',
 'ohmic_input_resistance_vb_ssse',
 'peak_indices',
 'peak_time',
 'peak_voltage',
 'postburst_adp_peak_indices',
 'postburst_adp_peak_values',
 'postburst_fast_ahp_indices',
 'postburst_fast_ahp_values',
 'postburst_min_indices',
 'postburst_min_values',
 'postburst_slow_ahp_indices',
 'postburst_slow_ahp_values',
 'sag_amplitude',
 'sag_ratio1',
 'sag_ratio2',
 'sag_time_constant',
 'spike_half_width',
 'spike_width2',
 'steady_state_current_stimend',
 'steady_state_hyper',
 'steady_state_voltage',
 'steady_state_voltage_stimend',
 'strict_burst_mean_freq',
 'strict_interburst_voltage',
 'time',
 'time_constant',
 'time_to_first_spike',
 'time_to_interburst_min',
 'time_to_last_spike',
 'time_to_postburst_adp_peak',
 'time_to_postburst_fast_ahp',
 'time_to_postburst_slow_ahp',
 'time_to_second_spike',
 'voltage',
 'voltage_after_stim',
 'voltage_base',
 'voltage_deflection',
 'voltage_deflection_begin',
 'voltage_deflection_vb_ssse',
 'voltage',
 'time',
 'current',
 'ISIs',
 'ISI_values',
 'ISI_CV',
 'single_burst_ratio',
 'irregularity_index',
 'burst_ISI_indices',
 'burst_mean_freq',
 'interburst_voltage',
 'ISI_log_slope',
 'ISI_semilog_slope',
 'ISI_log_slope_skip',
 'initburst_sahp',
 'initburst_sahp_vb',
 'initburst_sahp_ssse',
 'depol_block',
 'depol_block_bool',
 'Spikecount',
 'Spikecount_stimint',
 'spike_count',
 'spike_count_stimint',
 'spikes_per_burst',
 'spikes_per_burst_diff',
 'spikes_in_burst1_burst2_diff',
 'spikes_in_burst1_burstlast_diff',
 'impedance',
 'burst_number',
 'strict_burst_number',
 'trace_check',
 'phaseslope_max',
 'inv_ISI_values',
 'inv_first_ISI',
 'inv_second_ISI',
 'inv_third_ISI',
 'inv_fourth_ISI',
 'inv_fifth_ISI',
 'inv_last_ISI',
 'activation_time_constant',
 'deactivation_time_constant',
 'inactivation_time_constant']